id: P006785
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:22:47.654410
source_metadata:
  id: bdr:W1KG521
  title: ཟ་མ་མོའི་སྐྱིད་སྡུག་གངས་མ་ཆར།
  author: ''
  volumes:
    d8d7622154d6469abd6182fc6aee1270:
      image_group_id: I1KG532
      title: ''
      volume_number: 1
      total_pages: 280
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
